### ISSUE TITLE
Utilisation des drapeaux pour le changement de langue

### ISSUE THREAD

**Issue by dumbbell** [AuxQuatreCoinsDeParis/aux-quatre-coins-de-paris.fr#4]
Les deux drapeaux en PNG rajoutent deux requêtes pour pas grand chose. En plus, ils ne sont pas super beaux :-)

Peut-on les remplacer par du SVG inline par exemple ?

**Comment by Aurelielb** [comment]
On peut faire une sprite, ou tenter du svg mais ce dernier risque d'être un
peu lourd pour le drapeau anglais

**Comment by dumbbell** [comment]
Le drapeau britannique en SVG de Wikipedia fait 522 octets (contre 600 octets pour le PNG) :
https://upload.wikimedia.org/wikipedia/commons/a/ae/Flag_of_the_United_Kingdom.svg

Le drapeau français (même source) fait 249 octets (contre 268 octets pour le PNG) :
https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg

Ça semble pas mal, non ?

**Comment by Aurelielb** [comment]
yep, enfin je pensais essayer des les faire, mais bon, vu que c'est tout
prêt... ^^
